In [1]:
import numpy as np
def linear(x):
    return x
def linear_derivative(x):
    return np.ones_like(x)
activation = linear
activation_derivative = linear_derivative
X = np.array([[1, 1, 0, 1]])
y = np.array([[1]])
lr = 0.8
tolerance = 0.001
W1 = np.array([
    [0.3, 0.1],
    [-0.2, 0.4],
    [0.2, -0.3],
    [0.1, 0.4]
])
b1 = np.array([[0.2, 0.1]])
W2 = np.array([
    [0.3],
    [0.2]
])
b2 = np.array([[0.3]])
epoch = 0
first_epoch_printed = False
while True:
    epoch += 1
    z1 = np.dot(X, W1) + b1
    h = activation(z1)
    z2 = np.dot(h, W2) + b2
    o = linear(z2) 
    error = y - o
    delta_out = error * linear_derivative(o)
    delta_hidden = delta_out.dot(W2.T) * activation_derivative(h)
    W2 += lr * h.T.dot(delta_out)
    b2 += lr * delta_out
    W1 += lr * X.T.dot(delta_hidden)
    b1 += lr * delta_hidden
    if not first_epoch_printed:
        print("\n--- First Epoch ---")
        print("Epoch:", epoch)
        print("Output (o):", o)
        print("Error (D-o):", error)
        print("Updated W1:\n", W1)
        print("Updated b1:\n", b1)
        print("Updated W2:\n", W2)
        print("Updated b2:\n", b2)
        first_epoch_printed = True
    if abs(error[0][0]) < tolerance:
        print("\n--- Last Epoch (converged) ---")
        print("Epoch:", epoch)
        print("Output (o):", o)
        print("Error (D-o):", error)
        print("Updated W1:\n", W1)
        print("Updated b1:\n", b1)
        print("Updated W2:\n", W2)
        print("Updated b2:\n", b2)
        break



--- First Epoch ---
Epoch: 1
Output (o): [[0.62]]
Error (D-o): [[0.38]]
Updated W1:
 [[ 0.3912  0.1608]
 [-0.1088  0.4608]
 [ 0.2    -0.3   ]
 [ 0.1912  0.4608]]
Updated b1:
 [[0.2912 0.1608]]
Updated W2:
 [[0.4216]
 [0.504 ]]
Updated b2:
 [[0.604]]

--- Last Epoch (converged) ---
Epoch: 6
Output (o): [[0.9995037]]
Error (D-o): [[0.0004963]]
Updated W1:
 [[ 0.26790689 -0.08054948]
 [-0.23209311  0.21945052]
 [ 0.2        -0.3       ]
 [ 0.06790689  0.21945052]]
Updated b1:
 [[ 0.16790689 -0.08054948]]
Updated W2:
 [[0.11252367]
 [0.20877138]]
Updated b2:
 [[0.91148818]]
